Feature/c lightning
Start9Labs/ride-the-lightning-wrapper pull request #7
Opened 2021-07-29 23:17 UTC by chrisguida

Adds the ability to manage C-Lightning nodes, in addition to LND nodes. Most of the work here was getting the config to manage an arbitrary list of nodes of either type, rather than just a single LND node.

2021-08-27 18:06 UTC, ProofOfKeags requested changes

2021-08-27 18:06 UTC, ProofOfKeags commented on config_spec.yaml
> +  range: "[1,*)"
@dr-bonez is this a viable means of expressing list sizes?

2021-08-27 18:06 UTC, ProofOfKeags commented on config_spec.yaml
> +                nullable: false
Clean up heterogeneous use of `c-Lightning`, `C-Lightning`, `c-lightning` etc.

2021-08-27 18:06 UTC, ProofOfKeags commented on configurator/src/main.rs
> +                "userPersona": "MERCHANT",
We should probably change to "OPERATOR"

2021-08-27 18:06 UTC, ProofOfKeags commented on configurator/src/main.rs
> +        base_cfg.insert("host".into(), "0.0.0.0".into());
Don't use json as a working data structure. Create a datatype for the config data structure that RTL requires and assemble that. Serialize it at the end via a serde_json Serialize instance

2021-08-27 18:06 UTC, ProofOfKeags commented on configurator/src/main.rs
> +        serde_json::to_writer_pretty(File::create("/root/RTL-Config-new.json")?, base_cfg)?;
see above re: using json as a working data structure.

2021-08-27 18:06 UTC, ProofOfKeags commented on docker_entrypoint.sh
> +echo start9/shared >> /root/.backupignore
was this wrong before?

2021-08-27 18:06 UTC, ProofOfKeags commented on manifest.yaml
>      optional: Can alternatively configure an external LND node.
```suggestion
    optional: Can alternatively configure an external LND node or a C-Lightning node.
```

2021-08-27 18:06 UTC, ProofOfKeags commented on manifest.yaml
> +    optional: Can alternatively configure an external LND node.
```suggestion
    optional: Can alternatively configure an external C-Lightning node or LND node.
```

2021-08-27 18:45 UTC, dr-bonez commented on config_spec.yaml
> +  range: "[1,*)"
Yes

2021-08-27 20:08 UTC, chrisguida commented on config_spec.yaml
> +  range: "[1,*)"
Stolen straight from [TH](https://github.com/Start9Labs/thunderhub-wrapper/blob/1aeb50f6966817c20814e97d64b760136aa08b3c/config_spec.yaml#L16) :p

2021-08-27 20:12 UTC, chrisguida commented on config_spec.yaml
> +                nullable: false
Was trying to use "C-Lightning" for the lightning node and "c-lightning-REST" for the plugin, since that's how it appears in their Github URL. I'll change everything to "C-Lightning" since c-lightning-REST's [README](https://github.com/Ride-The-Lightning/c-lightning-REST/blob/master/README.md) says "C-Lightning-REST", and that's definitely prettier

2021-08-27 20:12 UTC, chrisguida commented on configurator/src/main.rs
> +                "userPersona": "MERCHANT",
Done

2021-08-27 20:17 UTC, chrisguida commented on docker_entrypoint.sh
> +echo start9/shared >> /root/.backupignore
Yes

2021-08-27 20:21 UTC, chrisguida commented on manifest.yaml
> +    optional: Can alternatively configure an external LND node.
What is this field for? It looks like maybe the LND description should be left how it is, and the C-Lightning description should be updated to say "Can alternatively configure ad external C-Lightning node."

2021-08-27 20:29 UTC, chrisguida commented on configurator/src/main.rs
> +        base_cfg.insert("host".into(), "0.0.0.0".into());
Oh, good idea. Was copying the pre-existing approach.

2021-08-27 20:39 UTC, ProofOfKeags commented on manifest.yaml
> +    optional: Can alternatively configure an external LND node.
The string is a description for why it is optional. If it is null, it is required. Installing C-Lightning is optional because you can use an external c-lightning node or *any* LND node. LND is optional because you can use an external LND node or *any* c-lightning node.

2021-08-27 20:40 UTC, ProofOfKeags commented on configurator/src/main.rs
> +        base_cfg.insert("host".into(), "0.0.0.0".into());
yeah I'm not sure who (could have been me) did it or why, but it's bad no matter what and since you're making substantial changes here anyway it's worth fixing.

2021-08-27 20:41 UTC, chrisguida commented on manifest.yaml
> +    optional: Can alternatively configure an external LND node.
Makes sense, will update

2021-08-27 20:57 UTC, chrisguida commented on configurator/src/main.rs
> +        base_cfg.insert("host".into(), "0.0.0.0".into());
Also need to remove `println!`s

2021-10-12 16:28 UTC, ProofOfKeags commented
My understanding is that this specific PR is obsoleted unless we are planning to ship this version of c-lightning for 0.2.x which I don't have any particular reason to justify.

Unless there are objections I'll be closing this tomorrow.

2021-12-08 01:40 UTC, chrisguida commented
@ProofOfKeags We can just rebase once the 030 branch gets merged

2021-12-16 16:07 UTC, chrisguida commented
Looks like this can go ahead. Just needs to be rebased on the 030 version, once that goes live: https://github.com/Start9Labs/ride-the-lightning-wrapper/pull/8

2022-05-27 00:53 UTC, chrisguida commented
Closing in favor of https://github.com/Start9Labs/ride-the-lightning-wrapper/pull/16

2022-05-27 00:53 UTC, closed without merging